/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2013-07-18 16:09:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class service_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	
	String path = request.getParameter("path");
	String viewType = request.getParameter("viewType");
	String offset = request.getParameter("offset");
	String limit = request.getParameter("limit");
	String reload = request.getParameter("reload");
	String tid = request.getParameter("tid");
	String smid = request.getParameter("smid");
	String webid = request.getParameter("webid");
	String append = request.getParameter("append");
	String datatype = request.getParameter("datatype");
	String maximize = request.getParameter("maximize");

	org.qanvas.CanvasView cv = new org.qanvas.CanvasView();
	cv.setViewType(viewType);
	cv.setPath(path);
	cv.setTargetId(tid);
	cv.setSourceModuleId(smid);
	if(request.getParameter("offset") != null) cv.setOffset(Integer.parseInt(offset));
	if(request.getParameter("limit") != null) cv.setLimit(Integer.parseInt(limit));
	if(request.getParameter("reload") != null) cv.setReload(request.getParameter("reload").equals("true"));
	if(request.getParameter("fr") != null) cv.setForcedReverse(request.getParameter("fr").equals("true"));
	if(datatype != null) cv.setDatatype(datatype);
	if(maximize != null) cv.setMaximize(maximize.equals("true"));
	cv.setAppend(append != null);
	if(path != null && path.length() > 0){
		response.setContentType("text/xml");
		String resolver = org.qanvas.GGGPathResolver.getViewData(cv, webid);
		out.write(resolver);
		return;
	}


      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
